### ISSUE TITLE
Re: Contributions

### ISSUE THREAD

**Issue by AsliRoy** [AB1908/CS-Books#1]
Let me get this straight. Contributions are not welcome at this point of time? xD

**Comment by AsliRoy** [comment]
@AB1908 , tagging you for a quicker reply.

**Comment by AB1908** [comment]
Uh, I'm busy?

**Comment by AB1908** [comment]
I plan to first cover a broad enough part of the curriculum and set up the structure. Otherwise I'll be getting haphazard PRs (if any).

**Comment by AsliRoy** [comment]
Why don't you just make a PR template then?
I am just suggesting this because there are a lot of things to be covered. Anyway, best of luck with this.

**Comment by AB1908** [comment]
Thanks. I'll try setting up a PR template. Seems like a good idea.
