### ISSUE TITLE
Migrate the contents of readme

### ISSUE THREAD

**Issue by AsliRoy** [AB1908/CS-Books#13]
Now that, the project has started attaining a structure, I guess the contents of readme can be migrated to curriculum.md and the new topics be added there only. It doesn't make sense to have two copies of the same does it?

**Comment by AsliRoy** [comment]
Do you want me to do the necessary changes and submit a PR? @AB1908

**Comment by AB1908** [comment]
Sounds good. I'll handle this one. Comment on the PR itself if you have further ideas.

**Comment by AB1908** [comment]
All done! Issue resolved!
